<?php

require_once("Model.php");
require_once("ActiveRecord.php");
require_once "Category.php";
require_once "User.php";
require_once "FileDeviceAssigned.php";
require_once "File.php";

/**
 * Class Device
 */
class Device extends ActiveRecord
{
    public $created_by;
    public $category_id;
    public $name;
    public $date_added;
    public $date_updated;
    public $visible = -1;
    private static $table_name = "devices";

    /**
     * @return string
     */
    public static function get_table_name()
    {
        return self::$table_name;
    }

    /**
     * Constructor.
     */
    public function __construct()
    {
        parent::__construct();
        $this->setTableName(Device::get_table_name());
    }

    /**
     * @return Model
     */
    public static function model()
    {
        $model = new Model(Device::$table_name, get_class(new Device()));

        return $model;
    }

    /**
     * Form data for model
     * @param File $files
     * @return array
     */
    public static function formData($files = array()) {
        return array(
            'created_by' => array(
                'type' => 'dropdown',
                'label' => 'Autor',
                'data' => Helpers::prepareDropDown(User::model()->findAll(), 'id', 'username')
            ),
            'category_id' => array(
                'type' => 'dropdown',
                'label' => "Kategorija",
                'data' => Helpers::prepareDropDown(Category::model()->findAll(), 'id', 'name')
            ),
            'name' => array(
                'type' => 'text',
                'label' => 'Naziv'
            ),
            'visible' => array(
                'type' => 'checkbox',
                'label' => 'Prikaži'
            ),
            'upload' => array(
                'type' => 'upload',
                'label' => 'Upload'
            ),
            'files' => array(
                'type' => 'images',
                'label' => 'Slike',
                'data' => $files
            )
        );
    }

    public function beforeSave()
    {
        parent::beforeSave(); // TODO: Change the autogenerated stub

        if($this->visible==-1) {
            $this->visible = 0;
        }

        $this->date_added = Helpers::time();
        $this->date_updated = Helpers::time();
    }

    /**
     * @return array
     */
    public function files() {
        $criteria = new Criteria();
        $criteria->setSelect("files.*, fda.*");
        $criteria->setJoin("LEFT JOIN files_devices_assigned fda ON fda.file_id=files.id
        LEFT JOIN devices d ON fda.device_id=d.id");
        $criteria->setCondition("d.id=:id");
        $criteria->addParam("id", $this->id);

        $files = File::model()->findAll($criteria);

        return is_array($files) ? $files:array($files);
    }
}