<?php

require_once("Model.php");
require_once("ActiveRecord.php");
require_once("UserRole.php");

/**
 * Class User
 */
class User extends ActiveRecord
{
    public $role_id;
    public $firstname;
    public $lastname;
    public $username;
    public $email;
    public $password;
    public $auth_key;
    public $active;
    public $date_added;
    public $date_updated;
    public $date_email_expire;
    private static $table_name = "users";

    /**
     * @return string
     */
    public static function get_table_name()
    {
        return self::$table_name;
    }

    /**
     * Constructor.
     */
    public function __construct()
    {
        parent::__construct();
        $this->setTableName(User::get_table_name());
    }

    /**
     * @return Model
     */
    public static function model()
    {
        $model = new Model(User::$table_name, get_class(new User()));

        return $model;
    }

    /**
     * Form data for model
     * @return array
     */
    public static function formData() {
        return array(
            'role_id' => array(
                'type' => 'dropdown',
                'label' => 'Uloga',
                'data' => Helpers::prepareDropDown(UserRole::model()->findAll(), 'id', 'name')
            ),
            'firstname' => array(
                'type' => 'text',
                'label' => 'Ime'
            ),
            'lastname' => array(
                'type' => 'text',
                'label' => "Prezime"
            ),
            'username' => array(
                'type' => 'text',
                'label' => 'Korisničko ime'
            ),
            'email' => array(
                'type' => 'email',
                'label' => 'Email'
            ),
            'password' => array(
                'type' => 'password',
                'label' => 'Lozinka'
            ),
            'active' => array(
                'type' => 'checkbox',
                'label' => 'Aktiviran'
            ),
            'date_email_expire' => array(
                'type' => 'date',
                'label' => 'Istek aktivacije'
            )
        );
    }

    /**
     * @param $token
     * @return array
     */

    public static function findByKey($token) {
        $criteria = new Criteria();
        $criteria->setCondition("auth_key=:token");
        $criteria->addParam("token", $token);

        $user = User::model()->findAll($criteria);

        return $user;
    }

    /**
     * @var UserRole $role
     * @return string
     */

    public function role() {
        if($this->role_id) {
            $role = UserRole::model()->findOne($this->role_id);

            return $role->name;
        } else {
            return "Guest";
        }
    }

    /**
     * Generate auth token for session
     */
    public function setAuthKey() {
        $this->auth_key = md5(Helpers::time().$this->get_table_name().$this->id.$this->username);
    }

    public function beforeSave()
    {
        parent::beforeSave(); // TODO: Change the autogenerated stub

        if(!$this->id) {
            $this->setAuthKey();
        }

        $this->date_added = Helpers::time();
        $this->date_updated = Helpers::time();
    }

    /**
     * @param $username
     * @param $password
     * @return array
     */

    public static function login($username, $password) {
        $criteria = new Criteria();
        $criteria->setCondition("username=:username AND password=:password AND active=1");
        $criteria->addParam("password", md5($password));
        $criteria->addParam("username", $username);

        $user = User::model()->findAll($criteria);

        return $user;
    }

    /**
     * Send activation email
     */
    public function sendEmail() {
        $to = $this->email;
        $subject = "Potvrda registracije";

        $message = 'Token za aktivaciju računa: https://barka.foi.hr/WebDiP/2015_projekti/WebDiP2015x005/backend/services/data/activation.php?token='.$this->auth_key;

        $headers = "MIME-Version: 1.0" . "\r\n";
        $headers .= "Content-type:text/html;charset=UTF-8" . "\r\n";

        $headers .= 'From: <projekt@foi.hr>' . "\r\n";

        mail($to,$subject,$message,$headers);
    }
}